//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anastesia
    {
        public Anastesia()
        {
            this.OrdenIntervencionDetalleAnastesias = new HashSet<OrdenIntervencionDetalleAnastesia>();
        }
    
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Horario { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<OrdenIntervencionDetalleAnastesia> OrdenIntervencionDetalleAnastesias { get; set; }
    }
}
