//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico
    {
        public Diagnostico()
        {
            this.Citas = new HashSet<Cita>();
            this.OrdenIntervencions = new HashSet<OrdenIntervencion>();
            this.OrdenIntervencions1 = new HashSet<OrdenIntervencion>();
        }
    
        public int CodigoDiagnostico { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Codigo_Enfermedad { get; set; }
        public Nullable<int> CodigoTipoDiagnostico { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual tipo_diagnostico tipo_diagnostico { get; set; }
        public virtual ENFERMEDAD ENFERMEDAD { get; set; }
        public virtual ICollection<OrdenIntervencion> OrdenIntervencions { get; set; }
        public virtual ICollection<OrdenIntervencion> OrdenIntervencions1 { get; set; }
    }
}
