//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENFERMEDAD
    {
        public ENFERMEDAD()
        {
            this.Diagnosticoes = new HashSet<Diagnostico>();
            this.enfermedad_insumo = new HashSet<enfermedad_insumo>();
        }
    
        public int Codigo_Enfermedad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Sintomas { get; set; }
        public string Causas { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<Diagnostico> Diagnosticoes { get; set; }
        public virtual ICollection<enfermedad_insumo> enfermedad_insumo { get; set; }
    }
}
