//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpicrisisDetalle
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoEpicrisis { get; set; }
        public Nullable<int> CodigoTipoInsumo { get; set; }
        public string Descripcion { get; set; }
        public string Observaciones { get; set; }
        public string Frecuencia { get; set; }
        public string Dosis { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual Epicrisi Epicrisi { get; set; }
        public virtual TipoInsumo TipoInsumo { get; set; }
    }
}
