//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epicrisi
    {
        public Epicrisi()
        {
            this.EpicrisisDetalles = new HashSet<EpicrisisDetalle>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> CodigoOrdenIntervencion { get; set; }
        public string AreaHospitalaria { get; set; }
        public string Servicio { get; set; }
        public string DiasEstancia { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public string Veterianario { get; set; }
        public string TratamientoRecibido { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> CodigoEstado { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<EpicrisisDetalle> EpicrisisDetalles { get; set; }
        public virtual OrdenIntervencion OrdenIntervencion { get; set; }
        public virtual EstadoEpicrisi EstadoEpicrisi { get; set; }
    }
}
