//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Epicrisis = new HashSet<Epicrisi>();
            this.Ficha_Hospitalizacion = new HashSet<Ficha_Hospitalizacion>();
            this.Informe_Riesgo_Quirurgico = new HashSet<Informe_Riesgo_Quirurgico>();
            this.InsumoRequeridoes = new HashSet<InsumoRequerido>();
            this.ProgramacionTurnoes = new HashSet<ProgramacionTurno>();
        }
    
        public int CodigoEstado { get; set; }
        public string TipoEstado { get; set; }
        public string DescripcionEstado { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<Epicrisi> Epicrisis { get; set; }
        public virtual ICollection<Ficha_Hospitalizacion> Ficha_Hospitalizacion { get; set; }
        public virtual ICollection<Informe_Riesgo_Quirurgico> Informe_Riesgo_Quirurgico { get; set; }
        public virtual ICollection<InsumoRequerido> InsumoRequeridoes { get; set; }
        public virtual ICollection<ProgramacionTurno> ProgramacionTurnoes { get; set; }
    }
}
