//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.InsumoRequeridoes = new HashSet<InsumoRequerido>();
        }
    
        public int CodigoEstado { get; set; }
        public string TipoEstado { get; set; }
        public string DescripcionEstado { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<InsumoRequerido> InsumoRequeridoes { get; set; }
    }
}
