//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estadia_Hospitalizacion
    {
        public int codigo_ficha { get; set; }
        public int codigo_sala { get; set; }
        public int codigo_cubiculo { get; set; }
        public string estado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual cubiculo cubiculo { get; set; }
        public virtual Ficha_Hospitalizacion Ficha_Hospitalizacion { get; set; }
        public virtual sala sala { get; set; }
    }
}
