//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha_Hospitalizacion
    {
        public Ficha_Hospitalizacion()
        {
            this.Estadia_Hospitalizacion = new HashSet<Estadia_Hospitalizacion>();
            this.Ficha_Hospitalizacion_Insumo = new HashSet<Ficha_Hospitalizacion_Insumo>();
        }
    
        public int codigo_ficha { get; set; }
        public Nullable<int> codigo_rq { get; set; }
        public Nullable<int> codigo_empleado { get; set; }
        public System.DateTime fecha_ficha { get; set; }
        public Nullable<int> codigo_cita { get; set; }
        public Nullable<int> codigoEmpleado_medico { get; set; }
        public Nullable<int> codigoEmpleado_tecnico { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual ICollection<Estadia_Hospitalizacion> Estadia_Hospitalizacion { get; set; }
        public virtual GG_Empleado GG_Empleado { get; set; }
        public virtual GG_Empleado GG_Empleado1 { get; set; }
        public virtual GG_Empleado GG_Empleado2 { get; set; }
        public virtual Riesgo_Quirurgico Riesgo_Quirurgico { get; set; }
        public virtual ICollection<Ficha_Hospitalizacion_Insumo> Ficha_Hospitalizacion_Insumo { get; set; }
    }
}
