//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAM_Informe_Medico
    {
        public int informe_medico { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public Nullable<int> codigo_mascota { get; set; }
        public Nullable<System.DateTime> fechaAtencion { get; set; }
        public string detalleInforme { get; set; }
        public string diagnostico { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
    }
}
