//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Tipo_Documento
    {
        public GCP_Tipo_Documento()
        {
            this.GG_Persona = new HashSet<GG_Persona>();
        }
    
        public int tipo_documento { get; set; }
        public string descrDocumento { get; set; }
    
        public virtual ICollection<GG_Persona> GG_Persona { get; set; }
    }
}
