//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCP_Raza
    {
        public GCP_Raza()
        {
            this.GCP_Mascota = new HashSet<GCP_Mascota>();
            this.GCP_Mascota1 = new HashSet<GCP_Mascota>();
        }
    
        public int codigo_raza { get; set; }
        public Nullable<int> codigo_especie { get; set; }
        public string nombreRaza { get; set; }
    
        public virtual ICollection<GCP_Mascota> GCP_Mascota { get; set; }
        public virtual ICollection<GCP_Mascota> GCP_Mascota1 { get; set; }
    }
}
