//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GG_Empleado
    {
        public GG_Empleado()
        {
            this.Ficha_Hospitalizacion = new HashSet<Ficha_Hospitalizacion>();
            this.Ficha_Hospitalizacion1 = new HashSet<Ficha_Hospitalizacion>();
            this.Ficha_Hospitalizacion2 = new HashSet<Ficha_Hospitalizacion>();
            this.ProgramacionTurnoDetalles = new HashSet<ProgramacionTurnoDetalle>();
            this.GPA_Solicitud = new HashSet<GPA_Solicitud>();
            this.GPA_Solicitud1 = new HashSet<GPA_Solicitud>();
            this.InsumoRequeridoes = new HashSet<InsumoRequerido>();
        }
    
        public int codigo_empleado { get; set; }
        public Nullable<int> codigo_persona { get; set; }
        public string cargo { get; set; }
        public string area { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<Ficha_Hospitalizacion> Ficha_Hospitalizacion { get; set; }
        public virtual ICollection<Ficha_Hospitalizacion> Ficha_Hospitalizacion1 { get; set; }
        public virtual ICollection<Ficha_Hospitalizacion> Ficha_Hospitalizacion2 { get; set; }
        public virtual ICollection<ProgramacionTurnoDetalle> ProgramacionTurnoDetalles { get; set; }
        public virtual GG_Persona GG_Persona { get; set; }
        public virtual ICollection<GPA_Solicitud> GPA_Solicitud { get; set; }
        public virtual ICollection<GPA_Solicitud> GPA_Solicitud1 { get; set; }
        public virtual ICollection<InsumoRequerido> InsumoRequeridoes { get; set; }
        public virtual Profesional Profesional { get; set; }
    }
}
