//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Camada
    {
        public int numero_camada { get; set; }
        public Nullable<int> solicitud_pedigri { get; set; }
        public Nullable<int> codigo_mascota { get; set; }
    
        public virtual GPA_Solicitud_Pedigri GPA_Solicitud_Pedigri { get; set; }
    }
}
