//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Solicitud
    {
        public GPA_Solicitud()
        {
            this.GPA_Declaracion_Jurada_Domicilio = new HashSet<GPA_Declaracion_Jurada_Domicilio>();
            this.GPA_Informe_Verificacion_Domicilio = new HashSet<GPA_Informe_Verificacion_Domicilio>();
            this.GPA_Registro_Resultados_KCP = new HashSet<GPA_Registro_Resultados_KCP>();
            this.GPA_Solicitud_Adopcion = new HashSet<GPA_Solicitud_Adopcion>();
            this.GPA_Solicitud_Cruces = new HashSet<GPA_Solicitud_Cruces>();
            this.GPA_Solicitud_Pedigri = new HashSet<GPA_Solicitud_Pedigri>();
        }
    
        public int numero_solicitud { get; set; }
        public Nullable<int> codigo_cliente { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public string comentarios { get; set; }
        public string estadoSolicitud { get; set; }
        public string tipoSolicitud { get; set; }
        public Nullable<int> UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual GCP_Cliente GCP_Cliente { get; set; }
        public virtual GG_Empleado GG_Empleado { get; set; }
        public virtual GG_Empleado GG_Empleado1 { get; set; }
        public virtual ICollection<GPA_Declaracion_Jurada_Domicilio> GPA_Declaracion_Jurada_Domicilio { get; set; }
        public virtual ICollection<GPA_Informe_Verificacion_Domicilio> GPA_Informe_Verificacion_Domicilio { get; set; }
        public virtual ICollection<GPA_Registro_Resultados_KCP> GPA_Registro_Resultados_KCP { get; set; }
        public virtual ICollection<GPA_Solicitud_Adopcion> GPA_Solicitud_Adopcion { get; set; }
        public virtual ICollection<GPA_Solicitud_Cruces> GPA_Solicitud_Cruces { get; set; }
        public virtual ICollection<GPA_Solicitud_Pedigri> GPA_Solicitud_Pedigri { get; set; }
    }
}
