//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPA_Informe_Verificacion_Domicilio
    {
        public int numero_informe_verificacion { get; set; }
        public Nullable<int> numero_solicitud { get; set; }
        public Nullable<System.DateTime> fechaInformeVerificacion { get; set; }
        public string direccionVerificacion { get; set; }
        public string Observaciones { get; set; }
        public string ResultadoInformeVerificacion { get; set; }
    
        public virtual GPA_Solicitud GPA_Solicitud { get; set; }
    }
}
