//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIA_CLINICA
    {
        public int CODIGO_HISTORIA_CLINICA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public int CODIGO_FICHA { get; set; }
        public string OBSERVACION { get; set; }
        public Nullable<bool> ESTADO_REGISTRO { get; set; }
    }
}
