//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Riesgo_Quirurgico
    {
        public Informe_Riesgo_Quirurgico()
        {
            this.Informe_Riesgo_Quirurgico_Detalle = new HashSet<Informe_Riesgo_Quirurgico_Detalle>();
        }
    
        public int codigo_rq { get; set; }
        public System.DateTime Fecha_Rq { get; set; }
        public string NombreInforme { get; set; }
        public Nullable<int> codigo_ficha { get; set; }
        public Nullable<int> codigo_Analisis_Preliminar { get; set; }
        public string complicaciones_rq { get; set; }
        public string consideraciones_particulares_rq { get; set; }
        public string clasificacion_riesgo_cardiaco { get; set; }
        public Nullable<int> codigo_empleado { get; set; }
        public Nullable<int> CodigoEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual GG_Empleado GG_Empleado { get; set; }
        public virtual InformeAnalisisPreliminar InformeAnalisisPreliminar { get; set; }
        public virtual ICollection<Informe_Riesgo_Quirurgico_Detalle> Informe_Riesgo_Quirurgico_Detalle { get; set; }
    }
}
