//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe_Riesgo_Quirurgico_Detalle
    {
        public int CodigoInformRQ { get; set; }
        public int CodigoRiesgoQuirurgico { get; set; }
        public string DetalleRiesgo { get; set; }
        public string Consider_Quirurgicas { get; set; }
        public string EstadoRiesgo { get; set; }
    
        public virtual Informe_Riesgo_Quirurgico Informe_Riesgo_Quirurgico { get; set; }
        public virtual Riesgo_Quirurgico Riesgo_Quirurgico { get; set; }
    }
}
