//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumoRequerido
    {
        public InsumoRequerido()
        {
            this.InsumoRequeridoDetalles = new HashSet<InsumoRequeridoDetalle>();
        }
    
        public int CodigoInsumoRequerido { get; set; }
        public string NombreInforme { get; set; }
        public Nullable<int> CodigoEmpleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Sustento { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> EstadoInformeInsumo { get; set; }
        public Nullable<int> CodigoEmpleadoEvaluador { get; set; }
        public Nullable<int> CodigoEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual GG_Empleado GG_Empleado { get; set; }
        public virtual ICollection<InsumoRequeridoDetalle> InsumoRequeridoDetalles { get; set; }
    }
}
