//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumoRequeridoDetalle
    {
        public int CodigoInsumoRequerido { get; set; }
        public int CodigoInsumo { get; set; }
        public int StockDisponible { get; set; }
        public int CantidadSolicitada { get; set; }
    
        public virtual Insumo Insumo { get; set; }
        public virtual InsumoRequerido InsumoRequerido { get; set; }
    }
}
