//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PETCENTEREntities1 : DbContext
    {
        public PETCENTEREntities1()
            : base("name=PETCENTEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anastesia> Anastesias { get; set; }
        public DbSet<Anio> Anios { get; set; }
        public DbSet<Cargo> Cargoes { get; set; }
        public DbSet<Diagnostico> Diagnosticoes { get; set; }
        public DbSet<Epicrisi> Epicrisis { get; set; }
        public DbSet<EpicrisisDetalle> EpicrisisDetalles { get; set; }
        public DbSet<EstadoEpicrisi> EstadoEpicrisis { get; set; }
        public DbSet<Me> Mes { get; set; }
        public DbSet<Operacion> Operacions { get; set; }
        public DbSet<OrdenIntervencion> OrdenIntervencions { get; set; }
        public DbSet<OrdenIntervencionDetalleAnastesia> OrdenIntervencionDetalleAnastesias { get; set; }
        public DbSet<OrdenIntervencionDetalleDiagnostico> OrdenIntervencionDetalleDiagnosticoes { get; set; }
        public DbSet<OrdenIntervencionDetalleOperacion> OrdenIntervencionDetalleOperacions { get; set; }
        public DbSet<OrdenIntervencionDetalleProfesional> OrdenIntervencionDetalleProfesionals { get; set; }
        public DbSet<OrdenIntervencionDetalleSignosVitale> OrdenIntervencionDetalleSignosVitales { get; set; }
        public DbSet<Profesional> Profesionals { get; set; }
        public DbSet<ProgramacionTurno> ProgramacionTurnoes { get; set; }
        public DbSet<ProgramacionTurnoDetalle> ProgramacionTurnoDetalles { get; set; }
        public DbSet<Sede> Sedes { get; set; }
        public DbSet<SignosVitale> SignosVitales { get; set; }
        public DbSet<TipoBusqueda> TipoBusquedas { get; set; }
        public DbSet<TipoInsumo> TipoInsumoes { get; set; }
        public DbSet<Turno> Turnoes { get; set; }
        public DbSet<Cita> Citas { get; set; }
        public DbSet<cubiculo> cubiculoes { get; set; }
        public DbSet<Estado> Estadoes { get; set; }
        public DbSet<Ficha_Hospitalizacion> Ficha_Hospitalizacion { get; set; }
        public DbSet<Ficha_Hospitalizacion_Insumo> Ficha_Hospitalizacion_Insumo { get; set; }
        public DbSet<GAM_Informe_Medico> GAM_Informe_Medico { get; set; }
        public DbSet<GCP_Cliente> GCP_Cliente { get; set; }
        public DbSet<GCP_Especie> GCP_Especie { get; set; }
        public DbSet<GCP_Mascota> GCP_Mascota { get; set; }
        public DbSet<GCP_Raza> GCP_Raza { get; set; }
        public DbSet<GCP_Tipo_Documento> GCP_Tipo_Documento { get; set; }
        public DbSet<GFC_Comprobante_Pago> GFC_Comprobante_Pago { get; set; }
        public DbSet<GG_Empleado> GG_Empleado { get; set; }
        public DbSet<GG_Persona> GG_Persona { get; set; }
        public DbSet<GPA_Camada> GPA_Camada { get; set; }
        public DbSet<GPA_Declaracion_Jurada_Domicilio> GPA_Declaracion_Jurada_Domicilio { get; set; }
        public DbSet<GPA_Detalle_Resultados_KCP> GPA_Detalle_Resultados_KCP { get; set; }
        public DbSet<GPA_Informe_Verificacion_Domicilio> GPA_Informe_Verificacion_Domicilio { get; set; }
        public DbSet<GPA_Registro_Resultados_KCP> GPA_Registro_Resultados_KCP { get; set; }
        public DbSet<GPA_Requisito_Domicilio> GPA_Requisito_Domicilio { get; set; }
        public DbSet<GPA_Solicitud> GPA_Solicitud { get; set; }
        public DbSet<GPA_Solicitud_Adopcion> GPA_Solicitud_Adopcion { get; set; }
        public DbSet<GPA_Solicitud_Cruces> GPA_Solicitud_Cruces { get; set; }
        public DbSet<GPA_Solicitud_Pedigri> GPA_Solicitud_Pedigri { get; set; }
        public DbSet<Insumo> Insumoes { get; set; }
        public DbSet<InsumoRequerido> InsumoRequeridoes { get; set; }
        public DbSet<InsumoRequeridoDetalle> InsumoRequeridoDetalles { get; set; }
        public DbSet<Riesgo_Quirurgico> Riesgo_Quirurgico { get; set; }
        public DbSet<sala> salas { get; set; }
        public DbSet<sala_cubiculo> sala_cubiculo { get; set; }
        public DbSet<Estadia_Hospitalizacion> Estadia_Hospitalizacion { get; set; }
    
        public virtual ObjectResult<USP_CONSULTAPROGRAMACION_Result> USP_CONSULTAPROGRAMACION(Nullable<int> codigoSede, Nullable<int> codigoAnio, Nullable<int> codigoMes)
        {
            var codigoSedeParameter = codigoSede.HasValue ?
                new ObjectParameter("CodigoSede", codigoSede) :
                new ObjectParameter("CodigoSede", typeof(int));
    
            var codigoAnioParameter = codigoAnio.HasValue ?
                new ObjectParameter("CodigoAnio", codigoAnio) :
                new ObjectParameter("CodigoAnio", typeof(int));
    
            var codigoMesParameter = codigoMes.HasValue ?
                new ObjectParameter("CodigoMes", codigoMes) :
                new ObjectParameter("CodigoMes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAPROGRAMACION_Result>("USP_CONSULTAPROGRAMACION", codigoSedeParameter, codigoAnioParameter, codigoMesParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEPROGRAMACIONTURNO_Result> USP_OBTENERDETALLEPROGRAMACIONTURNO(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEPROGRAMACIONTURNO_Result>("USP_OBTENERDETALLEPROGRAMACIONTURNO", codigoParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERPROGRAMACIONTURNO_Result> USP_OBTENERPROGRAMACIONTURNO(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERPROGRAMACIONTURNO_Result>("USP_OBTENERPROGRAMACIONTURNO", codigoParameter);
        }
    
        public virtual int USP_INSERTARDETALLEPROGRAMACIONTURNO(Nullable<int> codigo, Nullable<int> codigoTurno, Nullable<int> codigoCargo, Nullable<int> codigoEmpleado, Nullable<int> codigoProgramacionTurno, Nullable<bool> responsable, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoTurnoParameter = codigoTurno.HasValue ?
                new ObjectParameter("CodigoTurno", codigoTurno) :
                new ObjectParameter("CodigoTurno", typeof(int));
    
            var codigoCargoParameter = codigoCargo.HasValue ?
                new ObjectParameter("CodigoCargo", codigoCargo) :
                new ObjectParameter("CodigoCargo", typeof(int));
    
            var codigoEmpleadoParameter = codigoEmpleado.HasValue ?
                new ObjectParameter("CodigoEmpleado", codigoEmpleado) :
                new ObjectParameter("CodigoEmpleado", typeof(int));
    
            var codigoProgramacionTurnoParameter = codigoProgramacionTurno.HasValue ?
                new ObjectParameter("CodigoProgramacionTurno", codigoProgramacionTurno) :
                new ObjectParameter("CodigoProgramacionTurno", typeof(int));
    
            var responsableParameter = responsable.HasValue ?
                new ObjectParameter("Responsable", responsable) :
                new ObjectParameter("Responsable", typeof(bool));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARDETALLEPROGRAMACIONTURNO", codigoParameter, codigoTurnoParameter, codigoCargoParameter, codigoEmpleadoParameter, codigoProgramacionTurnoParameter, responsableParameter, accionParameter, codigoOut);
        }
    
        public virtual int USP_INSERTARPROGRAMACIONTURNO(Nullable<int> codigo, Nullable<int> codigoSede, Nullable<int> codigoAnio, Nullable<int> codigoMes, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoSedeParameter = codigoSede.HasValue ?
                new ObjectParameter("CodigoSede", codigoSede) :
                new ObjectParameter("CodigoSede", typeof(int));
    
            var codigoAnioParameter = codigoAnio.HasValue ?
                new ObjectParameter("CodigoAnio", codigoAnio) :
                new ObjectParameter("CodigoAnio", typeof(int));
    
            var codigoMesParameter = codigoMes.HasValue ?
                new ObjectParameter("CodigoMes", codigoMes) :
                new ObjectParameter("CodigoMes", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARPROGRAMACIONTURNO", codigoParameter, codigoSedeParameter, codigoAnioParameter, codigoMesParameter, fechaInicioParameter, fechaFinParameter, accionParameter, codigoOut);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISIS_Result> USP_CONSULTAEPICRISIS(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISIS_Result>("USP_CONSULTAEPICRISIS", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCION_Result> USP_CONSULTAORDENINTERVENCION(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCION_Result>("USP_CONSULTAORDENINTERVENCION", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual int USP_INSERTARDETALLEEPICRISIS(Nullable<int> codigo, Nullable<int> codigoEpicrisis, Nullable<int> codigoTipoInsumo, string descripcion, string observaciones, string frecuencia, string dosis, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoEpicrisisParameter = codigoEpicrisis.HasValue ?
                new ObjectParameter("CodigoEpicrisis", codigoEpicrisis) :
                new ObjectParameter("CodigoEpicrisis", typeof(int));
    
            var codigoTipoInsumoParameter = codigoTipoInsumo.HasValue ?
                new ObjectParameter("CodigoTipoInsumo", codigoTipoInsumo) :
                new ObjectParameter("CodigoTipoInsumo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var frecuenciaParameter = frecuencia != null ?
                new ObjectParameter("Frecuencia", frecuencia) :
                new ObjectParameter("Frecuencia", typeof(string));
    
            var dosisParameter = dosis != null ?
                new ObjectParameter("Dosis", dosis) :
                new ObjectParameter("Dosis", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARDETALLEEPICRISIS", codigoParameter, codigoEpicrisisParameter, codigoTipoInsumoParameter, descripcionParameter, observacionesParameter, frecuenciaParameter, dosisParameter, accionParameter, codigoOut);
        }
    
        public virtual int USP_INSERTAREPICRISIS(Nullable<int> codigo, Nullable<int> codigoOrdenIntervencion, string areaHospitalaria, string servicio, string diasEstancia, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaAlta, string veterinario, string tratamientoRecibido, string observaciones, Nullable<int> codigoEstado, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            var areaHospitalariaParameter = areaHospitalaria != null ?
                new ObjectParameter("AreaHospitalaria", areaHospitalaria) :
                new ObjectParameter("AreaHospitalaria", typeof(string));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("Servicio", servicio) :
                new ObjectParameter("Servicio", typeof(string));
    
            var diasEstanciaParameter = diasEstancia != null ?
                new ObjectParameter("DiasEstancia", diasEstancia) :
                new ObjectParameter("DiasEstancia", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("FechaAlta", fechaAlta) :
                new ObjectParameter("FechaAlta", typeof(System.DateTime));
    
            var veterinarioParameter = veterinario != null ?
                new ObjectParameter("Veterinario", veterinario) :
                new ObjectParameter("Veterinario", typeof(string));
    
            var tratamientoRecibidoParameter = tratamientoRecibido != null ?
                new ObjectParameter("TratamientoRecibido", tratamientoRecibido) :
                new ObjectParameter("TratamientoRecibido", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTAREPICRISIS", codigoParameter, codigoOrdenIntervencionParameter, areaHospitalariaParameter, servicioParameter, diasEstanciaParameter, fechaIngresoParameter, fechaAltaParameter, veterinarioParameter, tratamientoRecibidoParameter, observacionesParameter, codigoEstadoParameter, accionParameter, codigoOut);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEEPICRISIS_Result> USP_OBTENERDETALLEEPICRISIS(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEEPICRISIS_Result>("USP_OBTENERDETALLEEPICRISIS", codigoParameter);
        }
    
        public virtual ObjectResult<USP_OBTENEREPICRISIS_Result> USP_OBTENEREPICRISIS(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENEREPICRISIS_Result>("USP_OBTENEREPICRISIS", codigoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISFINAL_Result> USP_CONSULTAEPICRISISFINAL(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISFINAL_Result>("USP_CONSULTAEPICRISISFINAL", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV2_Result> USP_CONSULTAEPICRISISV2(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV2_Result>("USP_CONSULTAEPICRISISV2", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV3_Result> USP_CONSULTAEPICRISISV3(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, string codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV3_Result>("USP_CONSULTAEPICRISISV3", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV4_Result> USP_CONSULTAEPICRISISV4(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<int> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV4_Result>("USP_CONSULTAEPICRISISV4", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV2_Result> USP_CONSULTAORDENINTERVENCIONV2(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV2_Result>("USP_CONSULTAORDENINTERVENCIONV2", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV3_Result> USP_CONSULTAORDENINTERVENCIONV3(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV3_Result>("USP_CONSULTAORDENINTERVENCIONV3", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV4_Result> USP_CONSULTAORDENINTERVENCIONV4(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV4_Result>("USP_CONSULTAORDENINTERVENCIONV4", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEANASTESIA_Result> USP_OBTENERDETALLEANASTESIA(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEANASTESIA_Result>("USP_OBTENERDETALLEANASTESIA", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEDIAGNOSTICO_Result> USP_OBTENERDETALLEDIAGNOSTICO(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEDIAGNOSTICO_Result>("USP_OBTENERDETALLEDIAGNOSTICO", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEOPERACION_Result> USP_OBTENERDETALLEOPERACION(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEOPERACION_Result>("USP_OBTENERDETALLEOPERACION", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEPROFESIONAL_Result> USP_OBTENERDETALLEPROFESIONAL(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEPROFESIONAL_Result>("USP_OBTENERDETALLEPROFESIONAL", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLESIGNOSVITALES_Result> USP_OBTENERDETALLESIGNOSVITALES(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLESIGNOSVITALES_Result>("USP_OBTENERDETALLESIGNOSVITALES", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEORDENINTERVENCION_Result> USP_OBTENERDETALLEORDENINTERVENCION(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEORDENINTERVENCION_Result>("USP_OBTENERDETALLEORDENINTERVENCION", codigoOrdenIntervencionParameter);
        }
    
        public virtual int sp_AnularSolicitud(Nullable<int> numero_solicitud, Nullable<int> usuarioModificacion)
        {
            var numero_solicitudParameter = numero_solicitud.HasValue ?
                new ObjectParameter("numero_solicitud", numero_solicitud) :
                new ObjectParameter("numero_solicitud", typeof(int));
    
            var usuarioModificacionParameter = usuarioModificacion.HasValue ?
                new ObjectParameter("UsuarioModificacion", usuarioModificacion) :
                new ObjectParameter("UsuarioModificacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_AnularSolicitud", numero_solicitudParameter, usuarioModificacionParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarSolicitud_Result> sp_ConsultarSolicitud(Nullable<int> numero_solicitud, string nombres, string apellidoPaterno, string apellidoMaterno, Nullable<int> tipoDocumento, string numeroDocumento, Nullable<System.DateTime> fechaInicial, Nullable<System.DateTime> fechaFinal, string estadoSolicitud)
        {
            var numero_solicitudParameter = numero_solicitud.HasValue ?
                new ObjectParameter("numero_solicitud", numero_solicitud) :
                new ObjectParameter("numero_solicitud", typeof(int));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("apellidoPaterno", apellidoPaterno) :
                new ObjectParameter("apellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("apellidoMaterno", apellidoMaterno) :
                new ObjectParameter("apellidoMaterno", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(int));
    
            var numeroDocumentoParameter = numeroDocumento != null ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(string));
    
            var fechaInicialParameter = fechaInicial.HasValue ?
                new ObjectParameter("fechaInicial", fechaInicial) :
                new ObjectParameter("fechaInicial", typeof(System.DateTime));
    
            var fechaFinalParameter = fechaFinal.HasValue ?
                new ObjectParameter("fechaFinal", fechaFinal) :
                new ObjectParameter("fechaFinal", typeof(System.DateTime));
    
            var estadoSolicitudParameter = estadoSolicitud != null ?
                new ObjectParameter("estadoSolicitud", estadoSolicitud) :
                new ObjectParameter("estadoSolicitud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarSolicitud_Result>("sp_ConsultarSolicitud", numero_solicitudParameter, nombresParameter, apellidoPaternoParameter, apellidoMaternoParameter, tipoDocumentoParameter, numeroDocumentoParameter, fechaInicialParameter, fechaFinalParameter, estadoSolicitudParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerCamada_Result> sp_ObtenerCamada(Nullable<int> solicitud_pedigri)
        {
            var solicitud_pedigriParameter = solicitud_pedigri.HasValue ?
                new ObjectParameter("solicitud_pedigri", solicitud_pedigri) :
                new ObjectParameter("solicitud_pedigri", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerCamada_Result>("sp_ObtenerCamada", solicitud_pedigriParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerClientes_Result> sp_ObtenerClientes(string nombres, string apellidoPaterno, string apellidoMaterno, Nullable<int> tipoDocumento, string numeroDocumento)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidoPaternoParameter = apellidoPaterno != null ?
                new ObjectParameter("apellidoPaterno", apellidoPaterno) :
                new ObjectParameter("apellidoPaterno", typeof(string));
    
            var apellidoMaternoParameter = apellidoMaterno != null ?
                new ObjectParameter("apellidoMaterno", apellidoMaterno) :
                new ObjectParameter("apellidoMaterno", typeof(string));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("tipoDocumento", tipoDocumento) :
                new ObjectParameter("tipoDocumento", typeof(int));
    
            var numeroDocumentoParameter = numeroDocumento != null ?
                new ObjectParameter("numeroDocumento", numeroDocumento) :
                new ObjectParameter("numeroDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerClientes_Result>("sp_ObtenerClientes", nombresParameter, apellidoPaternoParameter, apellidoMaternoParameter, tipoDocumentoParameter, numeroDocumentoParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerMascotas_Result> sp_ObtenerMascotas(Nullable<int> codigo_cliente, string genero, string nombreMascota, string nombreRaza, string edadMayorIgual, string edadDias)
        {
            var codigo_clienteParameter = codigo_cliente.HasValue ?
                new ObjectParameter("codigo_cliente", codigo_cliente) :
                new ObjectParameter("codigo_cliente", typeof(int));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var nombreMascotaParameter = nombreMascota != null ?
                new ObjectParameter("nombreMascota", nombreMascota) :
                new ObjectParameter("nombreMascota", typeof(string));
    
            var nombreRazaParameter = nombreRaza != null ?
                new ObjectParameter("nombreRaza", nombreRaza) :
                new ObjectParameter("nombreRaza", typeof(string));
    
            var edadMayorIgualParameter = edadMayorIgual != null ?
                new ObjectParameter("EdadMayorIgual", edadMayorIgual) :
                new ObjectParameter("EdadMayorIgual", typeof(string));
    
            var edadDiasParameter = edadDias != null ?
                new ObjectParameter("EdadDias", edadDias) :
                new ObjectParameter("EdadDias", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerMascotas_Result>("sp_ObtenerMascotas", codigo_clienteParameter, generoParameter, nombreMascotaParameter, nombreRazaParameter, edadMayorIgualParameter, edadDiasParameter);
        }
    
        public virtual ObjectResult<sp_ObtenerRazas_Result> sp_ObtenerRazas(Nullable<int> codigo_especie, string nombreRaza)
        {
            var codigo_especieParameter = codigo_especie.HasValue ?
                new ObjectParameter("codigo_especie", codigo_especie) :
                new ObjectParameter("codigo_especie", typeof(int));
    
            var nombreRazaParameter = nombreRaza != null ?
                new ObjectParameter("nombreRaza", nombreRaza) :
                new ObjectParameter("nombreRaza", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObtenerRazas_Result>("sp_ObtenerRazas", codigo_especieParameter, nombreRazaParameter);
        }
    
        public virtual int sp_RegistrarCamada(Nullable<int> codigo_solicitud_pedigri, Nullable<int> codigo_mascota)
        {
            var codigo_solicitud_pedigriParameter = codigo_solicitud_pedigri.HasValue ?
                new ObjectParameter("codigo_solicitud_pedigri", codigo_solicitud_pedigri) :
                new ObjectParameter("codigo_solicitud_pedigri", typeof(int));
    
            var codigo_mascotaParameter = codigo_mascota.HasValue ?
                new ObjectParameter("codigo_mascota", codigo_mascota) :
                new ObjectParameter("codigo_mascota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarCamada", codigo_solicitud_pedigriParameter, codigo_mascotaParameter);
        }
    
        public virtual int sp_RegistrarSolicitud(Nullable<int> codigo_cliente, Nullable<int> codigo_mascota_padre, Nullable<int> codigo_mascota_madre, string comentarios, string tipoSolicitud, Nullable<int> usuarioCreacion, ObjectParameter codigo_solicitud)
        {
            var codigo_clienteParameter = codigo_cliente.HasValue ?
                new ObjectParameter("codigo_cliente", codigo_cliente) :
                new ObjectParameter("codigo_cliente", typeof(int));
    
            var codigo_mascota_padreParameter = codigo_mascota_padre.HasValue ?
                new ObjectParameter("codigo_mascota_padre", codigo_mascota_padre) :
                new ObjectParameter("codigo_mascota_padre", typeof(int));
    
            var codigo_mascota_madreParameter = codigo_mascota_madre.HasValue ?
                new ObjectParameter("codigo_mascota_madre", codigo_mascota_madre) :
                new ObjectParameter("codigo_mascota_madre", typeof(int));
    
            var comentariosParameter = comentarios != null ?
                new ObjectParameter("comentarios", comentarios) :
                new ObjectParameter("comentarios", typeof(string));
    
            var tipoSolicitudParameter = tipoSolicitud != null ?
                new ObjectParameter("tipoSolicitud", tipoSolicitud) :
                new ObjectParameter("tipoSolicitud", typeof(string));
    
            var usuarioCreacionParameter = usuarioCreacion.HasValue ?
                new ObjectParameter("UsuarioCreacion", usuarioCreacion) :
                new ObjectParameter("UsuarioCreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistrarSolicitud", codigo_clienteParameter, codigo_mascota_padreParameter, codigo_mascota_madreParameter, comentariosParameter, tipoSolicitudParameter, usuarioCreacionParameter, codigo_solicitud);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV5_Result> USP_CONSULTAEPICRISISV5(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<int> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV5_Result>("USP_CONSULTAEPICRISISV5", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    }
}
