//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PETCENTEREntities1 : DbContext
    {
        public PETCENTEREntities1()
            : base("name=PETCENTEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Anastesia> Anastesias { get; set; }
        public DbSet<Anio> Anios { get; set; }
        public DbSet<Cargo> Cargoes { get; set; }
        public DbSet<Diagnostico> Diagnosticoes { get; set; }
        public DbSet<Empleado> Empleadoes { get; set; }
        public DbSet<Epicrisi> Epicrisis { get; set; }
        public DbSet<EpicrisisDetalle> EpicrisisDetalles { get; set; }
        public DbSet<EstadoEpicrisi> EstadoEpicrisis { get; set; }
        public DbSet<Me> Mes { get; set; }
        public DbSet<Operacion> Operacions { get; set; }
        public DbSet<OrdenIntervencion> OrdenIntervencions { get; set; }
        public DbSet<OrdenIntervencionDetalleAnastesia> OrdenIntervencionDetalleAnastesias { get; set; }
        public DbSet<OrdenIntervencionDetalleDiagnostico> OrdenIntervencionDetalleDiagnosticoes { get; set; }
        public DbSet<OrdenIntervencionDetalleOperacion> OrdenIntervencionDetalleOperacions { get; set; }
        public DbSet<OrdenIntervencionDetalleProfesional> OrdenIntervencionDetalleProfesionals { get; set; }
        public DbSet<OrdenIntervencionDetalleSignosVitale> OrdenIntervencionDetalleSignosVitales { get; set; }
        public DbSet<Profesional> Profesionals { get; set; }
        public DbSet<ProgramacionTurno> ProgramacionTurnoes { get; set; }
        public DbSet<ProgramacionTurnoDetalle> ProgramacionTurnoDetalles { get; set; }
        public DbSet<Sede> Sedes { get; set; }
        public DbSet<SignosVitale> SignosVitales { get; set; }
        public DbSet<TipoBusqueda> TipoBusquedas { get; set; }
        public DbSet<TipoInsumo> TipoInsumoes { get; set; }
        public DbSet<Turno> Turnoes { get; set; }
    
        public virtual ObjectResult<USP_CONSULTAPROGRAMACION_Result> USP_CONSULTAPROGRAMACION(Nullable<int> codigoSede, Nullable<int> codigoAnio, Nullable<int> codigoMes)
        {
            var codigoSedeParameter = codigoSede.HasValue ?
                new ObjectParameter("CodigoSede", codigoSede) :
                new ObjectParameter("CodigoSede", typeof(int));
    
            var codigoAnioParameter = codigoAnio.HasValue ?
                new ObjectParameter("CodigoAnio", codigoAnio) :
                new ObjectParameter("CodigoAnio", typeof(int));
    
            var codigoMesParameter = codigoMes.HasValue ?
                new ObjectParameter("CodigoMes", codigoMes) :
                new ObjectParameter("CodigoMes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAPROGRAMACION_Result>("USP_CONSULTAPROGRAMACION", codigoSedeParameter, codigoAnioParameter, codigoMesParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEPROGRAMACIONTURNO_Result> USP_OBTENERDETALLEPROGRAMACIONTURNO(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEPROGRAMACIONTURNO_Result>("USP_OBTENERDETALLEPROGRAMACIONTURNO", codigoParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERPROGRAMACIONTURNO_Result> USP_OBTENERPROGRAMACIONTURNO(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERPROGRAMACIONTURNO_Result>("USP_OBTENERPROGRAMACIONTURNO", codigoParameter);
        }
    
        public virtual int USP_INSERTARDETALLEPROGRAMACIONTURNO(Nullable<int> codigo, Nullable<int> codigoTurno, Nullable<int> codigoCargo, Nullable<int> codigoEmpleado, Nullable<int> codigoProgramacionTurno, Nullable<bool> responsable, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoTurnoParameter = codigoTurno.HasValue ?
                new ObjectParameter("CodigoTurno", codigoTurno) :
                new ObjectParameter("CodigoTurno", typeof(int));
    
            var codigoCargoParameter = codigoCargo.HasValue ?
                new ObjectParameter("CodigoCargo", codigoCargo) :
                new ObjectParameter("CodigoCargo", typeof(int));
    
            var codigoEmpleadoParameter = codigoEmpleado.HasValue ?
                new ObjectParameter("CodigoEmpleado", codigoEmpleado) :
                new ObjectParameter("CodigoEmpleado", typeof(int));
    
            var codigoProgramacionTurnoParameter = codigoProgramacionTurno.HasValue ?
                new ObjectParameter("CodigoProgramacionTurno", codigoProgramacionTurno) :
                new ObjectParameter("CodigoProgramacionTurno", typeof(int));
    
            var responsableParameter = responsable.HasValue ?
                new ObjectParameter("Responsable", responsable) :
                new ObjectParameter("Responsable", typeof(bool));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARDETALLEPROGRAMACIONTURNO", codigoParameter, codigoTurnoParameter, codigoCargoParameter, codigoEmpleadoParameter, codigoProgramacionTurnoParameter, responsableParameter, accionParameter, codigoOut);
        }
    
        public virtual int USP_INSERTARPROGRAMACIONTURNO(Nullable<int> codigo, Nullable<int> codigoSede, Nullable<int> codigoAnio, Nullable<int> codigoMes, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoSedeParameter = codigoSede.HasValue ?
                new ObjectParameter("CodigoSede", codigoSede) :
                new ObjectParameter("CodigoSede", typeof(int));
    
            var codigoAnioParameter = codigoAnio.HasValue ?
                new ObjectParameter("CodigoAnio", codigoAnio) :
                new ObjectParameter("CodigoAnio", typeof(int));
    
            var codigoMesParameter = codigoMes.HasValue ?
                new ObjectParameter("CodigoMes", codigoMes) :
                new ObjectParameter("CodigoMes", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARPROGRAMACIONTURNO", codigoParameter, codigoSedeParameter, codigoAnioParameter, codigoMesParameter, fechaInicioParameter, fechaFinParameter, accionParameter, codigoOut);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISIS_Result> USP_CONSULTAEPICRISIS(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISIS_Result>("USP_CONSULTAEPICRISIS", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCION_Result> USP_CONSULTAORDENINTERVENCION(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<System.DateTime> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCION_Result>("USP_CONSULTAORDENINTERVENCION", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual int USP_INSERTARDETALLEEPICRISIS(Nullable<int> codigo, Nullable<int> codigoEpicrisis, Nullable<int> codigoTipoInsumo, string descripcion, string observaciones, string frecuencia, string dosis, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoEpicrisisParameter = codigoEpicrisis.HasValue ?
                new ObjectParameter("CodigoEpicrisis", codigoEpicrisis) :
                new ObjectParameter("CodigoEpicrisis", typeof(int));
    
            var codigoTipoInsumoParameter = codigoTipoInsumo.HasValue ?
                new ObjectParameter("CodigoTipoInsumo", codigoTipoInsumo) :
                new ObjectParameter("CodigoTipoInsumo", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var frecuenciaParameter = frecuencia != null ?
                new ObjectParameter("Frecuencia", frecuencia) :
                new ObjectParameter("Frecuencia", typeof(string));
    
            var dosisParameter = dosis != null ?
                new ObjectParameter("Dosis", dosis) :
                new ObjectParameter("Dosis", typeof(string));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTARDETALLEEPICRISIS", codigoParameter, codigoEpicrisisParameter, codigoTipoInsumoParameter, descripcionParameter, observacionesParameter, frecuenciaParameter, dosisParameter, accionParameter, codigoOut);
        }
    
        public virtual int USP_INSERTAREPICRISIS(Nullable<int> codigo, Nullable<int> codigoOrdenIntervencion, string areaHospitalaria, string servicio, string diasEstancia, Nullable<System.DateTime> fechaIngreso, Nullable<System.DateTime> fechaAlta, string veterinario, string tratamientoRecibido, string observaciones, Nullable<int> codigoEstado, string accion, ObjectParameter codigoOut)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            var areaHospitalariaParameter = areaHospitalaria != null ?
                new ObjectParameter("AreaHospitalaria", areaHospitalaria) :
                new ObjectParameter("AreaHospitalaria", typeof(string));
    
            var servicioParameter = servicio != null ?
                new ObjectParameter("Servicio", servicio) :
                new ObjectParameter("Servicio", typeof(string));
    
            var diasEstanciaParameter = diasEstancia != null ?
                new ObjectParameter("DiasEstancia", diasEstancia) :
                new ObjectParameter("DiasEstancia", typeof(string));
    
            var fechaIngresoParameter = fechaIngreso.HasValue ?
                new ObjectParameter("FechaIngreso", fechaIngreso) :
                new ObjectParameter("FechaIngreso", typeof(System.DateTime));
    
            var fechaAltaParameter = fechaAlta.HasValue ?
                new ObjectParameter("FechaAlta", fechaAlta) :
                new ObjectParameter("FechaAlta", typeof(System.DateTime));
    
            var veterinarioParameter = veterinario != null ?
                new ObjectParameter("Veterinario", veterinario) :
                new ObjectParameter("Veterinario", typeof(string));
    
            var tratamientoRecibidoParameter = tratamientoRecibido != null ?
                new ObjectParameter("TratamientoRecibido", tratamientoRecibido) :
                new ObjectParameter("TratamientoRecibido", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERTAREPICRISIS", codigoParameter, codigoOrdenIntervencionParameter, areaHospitalariaParameter, servicioParameter, diasEstanciaParameter, fechaIngresoParameter, fechaAltaParameter, veterinarioParameter, tratamientoRecibidoParameter, observacionesParameter, codigoEstadoParameter, accionParameter, codigoOut);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEEPICRISIS_Result> USP_OBTENERDETALLEEPICRISIS(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEEPICRISIS_Result>("USP_OBTENERDETALLEEPICRISIS", codigoParameter);
        }
    
        public virtual ObjectResult<USP_OBTENEREPICRISIS_Result> USP_OBTENEREPICRISIS(Nullable<int> codigo)
        {
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENEREPICRISIS_Result>("USP_OBTENEREPICRISIS", codigoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISFINAL_Result> USP_CONSULTAEPICRISISFINAL(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISFINAL_Result>("USP_CONSULTAEPICRISISFINAL", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV2_Result> USP_CONSULTAEPICRISISV2(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<System.DateTime> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV2_Result>("USP_CONSULTAEPICRISISV2", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV3_Result> USP_CONSULTAEPICRISISV3(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, string codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV3_Result>("USP_CONSULTAEPICRISISV3", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAEPICRISISV4_Result> USP_CONSULTAEPICRISISV4(Nullable<System.DateTime> fechaIngresoInicio, Nullable<System.DateTime> fechaIngresoFin, Nullable<int> codigo, string nombre, Nullable<int> codigoEstado)
        {
            var fechaIngresoInicioParameter = fechaIngresoInicio.HasValue ?
                new ObjectParameter("FechaIngresoInicio", fechaIngresoInicio) :
                new ObjectParameter("FechaIngresoInicio", typeof(System.DateTime));
    
            var fechaIngresoFinParameter = fechaIngresoFin.HasValue ?
                new ObjectParameter("FechaIngresoFin", fechaIngresoFin) :
                new ObjectParameter("FechaIngresoFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoEstadoParameter = codigoEstado.HasValue ?
                new ObjectParameter("CodigoEstado", codigoEstado) :
                new ObjectParameter("CodigoEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAEPICRISISV4_Result>("USP_CONSULTAEPICRISISV4", fechaIngresoInicioParameter, fechaIngresoFinParameter, codigoParameter, nombreParameter, codigoEstadoParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV2_Result> USP_CONSULTAORDENINTERVENCIONV2(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV2_Result>("USP_CONSULTAORDENINTERVENCIONV2", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV3_Result> USP_CONSULTAORDENINTERVENCIONV3(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV3_Result>("USP_CONSULTAORDENINTERVENCIONV3", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_CONSULTAORDENINTERVENCIONV4_Result> USP_CONSULTAORDENINTERVENCIONV4(Nullable<int> codigoIntervencion, Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> codigo, string nombre)
        {
            var codigoIntervencionParameter = codigoIntervencion.HasValue ?
                new ObjectParameter("CodigoIntervencion", codigoIntervencion) :
                new ObjectParameter("CodigoIntervencion", typeof(int));
    
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var codigoParameter = codigo.HasValue ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_CONSULTAORDENINTERVENCIONV4_Result>("USP_CONSULTAORDENINTERVENCIONV4", codigoIntervencionParameter, fechaInicioParameter, fechaFinParameter, codigoParameter, nombreParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEANASTESIA_Result> USP_OBTENERDETALLEANASTESIA(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEANASTESIA_Result>("USP_OBTENERDETALLEANASTESIA", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEDIAGNOSTICO_Result> USP_OBTENERDETALLEDIAGNOSTICO(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEDIAGNOSTICO_Result>("USP_OBTENERDETALLEDIAGNOSTICO", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEOPERACION_Result> USP_OBTENERDETALLEOPERACION(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEOPERACION_Result>("USP_OBTENERDETALLEOPERACION", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEPROFESIONAL_Result> USP_OBTENERDETALLEPROFESIONAL(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEPROFESIONAL_Result>("USP_OBTENERDETALLEPROFESIONAL", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLESIGNOSVITALES_Result> USP_OBTENERDETALLESIGNOSVITALES(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLESIGNOSVITALES_Result>("USP_OBTENERDETALLESIGNOSVITALES", codigoOrdenIntervencionParameter);
        }
    
        public virtual ObjectResult<USP_OBTENERDETALLEORDENINTERVENCION_Result> USP_OBTENERDETALLEORDENINTERVENCION(Nullable<int> codigoOrdenIntervencion)
        {
            var codigoOrdenIntervencionParameter = codigoOrdenIntervencion.HasValue ?
                new ObjectParameter("CodigoOrdenIntervencion", codigoOrdenIntervencion) :
                new ObjectParameter("CodigoOrdenIntervencion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_OBTENERDETALLEORDENINTERVENCION_Result>("USP_OBTENERDETALLEORDENINTERVENCION", codigoOrdenIntervencionParameter);
        }
    }
}
