//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenIntervencion
    {
        public OrdenIntervencion()
        {
            this.Epicrisis = new HashSet<Epicrisi>();
            this.OrdenIntervencionDetalleAnastesias = new HashSet<OrdenIntervencionDetalleAnastesia>();
            this.OrdenIntervencionDetalleDiagnosticoes = new HashSet<OrdenIntervencionDetalleDiagnostico>();
            this.OrdenIntervencionDetalleOperacions = new HashSet<OrdenIntervencionDetalleOperacion>();
            this.OrdenIntervencionDetalleProfesionals = new HashSet<OrdenIntervencionDetalleProfesional>();
            this.OrdenIntervencionDetalleSignosVitales = new HashSet<OrdenIntervencionDetalleSignosVitale>();
        }
    
        public int Codigo { get; set; }
        public string NumeroHistoriaClinica { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public string Edad { get; set; }
        public string Peso { get; set; }
        public string Raza { get; set; }
        public string Tipo { get; set; }
        public string Cliente { get; set; }
        public string Paciente { get; set; }
        public Nullable<System.DateTime> FechaIntervencion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<Epicrisi> Epicrisis { get; set; }
        public virtual ICollection<OrdenIntervencionDetalleAnastesia> OrdenIntervencionDetalleAnastesias { get; set; }
        public virtual ICollection<OrdenIntervencionDetalleDiagnostico> OrdenIntervencionDetalleDiagnosticoes { get; set; }
        public virtual ICollection<OrdenIntervencionDetalleOperacion> OrdenIntervencionDetalleOperacions { get; set; }
        public virtual ICollection<OrdenIntervencionDetalleProfesional> OrdenIntervencionDetalleProfesionals { get; set; }
        public virtual ICollection<OrdenIntervencionDetalleSignosVitale> OrdenIntervencionDetalleSignosVitales { get; set; }
    }
}
