//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesional
    {
        public Profesional()
        {
            this.OrdenIntervencionDetalleProfesionals = new HashSet<OrdenIntervencionDetalleProfesional>();
        }
    
        public int Codigo { get; set; }
        public Nullable<int> NumeroOrden { get; set; }
        public string DNI { get; set; }
        public string Profesional1 { get; set; }
        public string Especialidad { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual ICollection<OrdenIntervencionDetalleProfesional> OrdenIntervencionDetalleProfesionals { get; set; }
    }
}
