//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramacionTurnoDetalle
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoTurno { get; set; }
        public Nullable<int> CodigoCargo { get; set; }
        public Nullable<int> CodigoEmpleado { get; set; }
        public Nullable<int> CodigoProgramacionTurno { get; set; }
        public Nullable<bool> Responsable { get; set; }
        public Nullable<bool> EstadoRegistro { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual ProgramacionTurno ProgramacionTurno { get; set; }
        public virtual Turno Turno { get; set; }
        public virtual GG_Empleado GG_Empleado { get; set; }
    }
}
