//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Riesgo_Quirurgico
    {
        public Riesgo_Quirurgico()
        {
            this.Ficha_Hospitalizacion = new HashSet<Ficha_Hospitalizacion>();
        }
    
        public int codigo_rq { get; set; }
        public System.DateTime fecha_rq { get; set; }
        public string complicaciones_rq { get; set; }
        public string consideraciones_particulares_rq { get; set; }
        public string clasificacion_riesgo_cardiaco { get; set; }
    
        public virtual ICollection<Ficha_Hospitalizacion> Ficha_Hospitalizacion { get; set; }
    }
}
