//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pet.Data.EF5.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        public sala()
        {
            this.Estadia_Hospitalizacion = new HashSet<Estadia_Hospitalizacion>();
            this.sala_cubiculo = new HashSet<sala_cubiculo>();
        }
    
        public int codigo_sala { get; set; }
        public string nombre_sala { get; set; }
        public string observacion_sala { get; set; }
        public string tipo_sala { get; set; }
        public string estado_sala { get; set; }
    
        public virtual ICollection<Estadia_Hospitalizacion> Estadia_Hospitalizacion { get; set; }
        public virtual ICollection<sala_cubiculo> sala_cubiculo { get; set; }
    }
}
